# Generated by Django 5.1.1 on 2024-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo1',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
