# Generated by Django 5.1.1 on 2024-11-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0002_remove_profile_imagen_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
