# Generated by Django 5.1.3 on 2024-11-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
