# Generated by Django 5.1.3 on 2024-12-01 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0002_delete_profileimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('email_usuario', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel1_usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('tel2_usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('imagen_usuario', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
