# Generated by Django 5.1.3 on 2024-12-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0022_alter_categ_producto_nombre_alter_producto_categoria'),
        ('opiniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={},
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='libro',
        ),
        migrations.AddField(
            model_name='opinion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='CarritoApp.producto'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
