# Generated by Django 5.1.3 on 2024-12-04 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0022_alter_categ_producto_nombre_alter_producto_categoria'),
        ('opiniones', '0004_producto_alter_opinion_usuario_alter_opinion_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarritoApp.producto'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='opinion',
            table=None,
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
