# Generated by Django 5.1.1 on 2024-11-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0001_initial'),
    ]

    operations = [
    ]
