# Generated by Django 5.1.1 on 2024-11-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0003_provedor_alter_venta_factura_venta_compra_provedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categ_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
