# Generated by Django 5.1.1 on 2024-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0007_remove_producto_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(default='Nombre del producto', max_length=200),
        ),
    ]
