# Generated by Django 5.1.1 on 2024-11-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0009_compra_stock_alter_compra_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='factura_compra',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarritoApp.producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='provedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarritoApp.provedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(default='Nombre del producto', max_length=200),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='factura_venta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
