# Generated by Django 5.1.1 on 2024-11-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0010_producto_stock_alter_compra_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='stock',
        ),
        migrations.AlterField(
            model_name='compra',
            name='factura_compra',
            field=models.CharField(max_length=100),
        ),
    ]
