# Generated by Django 5.1.1 on 2024-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0011_remove_compra_stock_alter_compra_factura_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fecha_venta',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='precio_venta',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='factura_venta',
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
