# Generated by Django 5.1.1 on 2024-11-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0019_remove_factura_productos_factura_detalle_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(),
        ),
    ]
