# Generated by Django 5.1.3 on 2024-12-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0021_factura_imagen_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ_producto',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='CarritoApp.categ_producto'),
        ),
    ]
